name: 🚀 Deploy Portfolio to DreamHost (Production)

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          protocol: ftps
          server: ${{ secrets.SFTP_HOST }}
          port: 21
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: /home/yasserious/yasserious.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            Workflows/**
            .github/**
            README.md
